# Generated by Django 5.1.3 on 2025-02-03 22:11
import uuid
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Descrição"),
                ),
                ("init_date", models.DateTimeField(verbose_name="Início da atividade")),
                ("end_date", models.DateTimeField(verbose_name="Fim da atividade")),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Active"), ("P", "Pending"), ("C", "Closed")],
                        default="P",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tag_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "activity_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Descrição"),
                ),
                ("init_date", models.DateTimeField(verbose_name="Início da atividade")),
                ("end_date", models.DateTimeField(verbose_name="Fim da atividade")),
                (
                    "instructor",
                    models.CharField(max_length=100, verbose_name="Monitor"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(to="management.tag"),
        ),
    ]
