# Generated by Django 5.1.3 on 2025-02-13 10:04

import datetime
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Descrição"),
                ),
                ("init_date", models.DateTimeField(verbose_name="Início da atividade")),
                ("end_date", models.DateTimeField(verbose_name="Fim da atividade")),
                (
                    "instructor",
                    models.CharField(max_length=150, verbose_name="Monitor"),
                ),
                (
                    "estimated_duration",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
            ],
            options={
                "verbose_name_plural": "Atividades",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Descrição"),
                ),
                ("init_date", models.DateTimeField(verbose_name="Início da atividade")),
                ("end_date", models.DateTimeField(verbose_name="Fim da atividade")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Ativo"),
                            ("closed", "Encerrado"),
                            ("canceled", "Cancelado"),
                            ("draft", "Rascunho"),
                            ("approved", "Aprovado"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tag_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.activity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Certificados",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(to="management.tag"),
        ),
    ]
