# Generated by Django 5.1.3 on 2025-02-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_activity_estimated_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("closed", "Encerrado"),
                    ("canceled", "Cancelado"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
