# Generated by Django 5.1.3 on 2025-02-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_activity_estimated_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="duration",
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("closed", "Encerrado"),
                    ("canceled", "Cancelado"),
                    ("draft", "Rascunho"),
                ],
                default="draft",
                max_length=50,
                verbose_name="",
            ),
        ),
    ]
