# Generated by Django 5.1.3 on 2025-02-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_event_status"),
        ("management", "0003_remove_certificate_duration_alter_event_status"),
    ]

    operations = []
