# Generated by Django 5.1.3 on 2025-02-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="banner",
            field=models.ImageField(
                blank=True,
                default="/static/images/event-banner-default.png",
                null=True,
                upload_to="events/banners/",
            ),
        ),
    ]
