# Generated by Django 5.1.3 on 2025-02-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_merge_20250206_1515"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Atividades"},
        ),
        migrations.AlterModelOptions(
            name="certificate",
            options={"verbose_name_plural": "Certificados"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name_plural": "Eventos"},
        ),
        migrations.AlterField(
            model_name="activity",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("closed", "Encerrado"),
                    ("canceled", "Cancelado"),
                    ("draft", "Rascunho"),
                    ("approved", "Aprovado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="",
            ),
        ),
    ]
