# Generated by Django 5.1.3 on 2025-02-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_event_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="capacity",
            field=models.IntegerField(default=0, verbose_name="Capacidade"),
        ),
    ]
