# Generated by Django 5.1.3 on 2025-02-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_activity_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="campus",
            field=models.CharField(default="null", max_length=50),
        ),
    ]
