# Generated by Django 5.1.3 on 2025-02-19 01:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_certificate_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Descrição"),
                ),
            ],
        ),
    ]
