# Generated by Django 5.1.3 on 2025-02-19 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_activitytype"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="management.activitytype",
                verbose_name="Tipo",
            ),
        ),
    ]
