# Generated by Django 5.1.3 on 2025-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_activity_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="campus",
            field=models.CharField(
                choices=[
                    ("null", "Null"),
                    ("AP", "Apodi"),
                    ("CA", "Caicó"),
                    ("CG", "Canguaretama"),
                    ("CM", "Ceará-Mirim"),
                    ("CN", "Currais Novos"),
                    ("IP", "Ipanguaçu"),
                    ("JC", "João Câmara"),
                    ("JU", "Jucurutu"),
                    ("LA", "Lajes"),
                    ("MA", "Macau"),
                    ("MO", "Mossoró"),
                    ("NC", "Natal - Central"),
                    ("NCA", "Natal - Cidade Alta"),
                    ("NZL", "Natal - Zona Leste"),
                    ("NZN", "Natal - Zona Norte"),
                    ("NV", "Nova Cruz"),
                    ("PA", "Parelhas"),
                    ("PM", "Parnamirim"),
                    ("PF", "Pau dos Ferros"),
                    ("SC", "Santa Cruz"),
                    ("SG", "São Gonçalo do Amarante"),
                    ("SP", "São Paulo do Potengi"),
                ],
                default="null",
                max_length=50,
            ),
        ),
    ]
