# Generated by Django 5.1.3 on 2025-02-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_alter_certificate_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="management.activity"
            ),
        ),
    ]
