# Generated by Django 5.1.3 on 2025-02-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_alter_certificate_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="management.activity"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="banner",
            field=models.ImageField(
                default="events/banners/event-banner-default.jpg",
                upload_to="events/banners/",
                verbose_name="Banner",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("closed", "Encerrado"),
                    ("canceled", "Cancelado"),
                    ("draft", "Não aprovado"),
                    ("approved", "Aprovado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="",
            ),
        ),
    ]
