# Generated by Django 5.1.3 on 2025-02-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_certificate_image_alter_certificate_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["init_date"], "verbose_name_plural": "Eventos"},
        ),
        migrations.AlterField(
            model_name="event",
            name="banner",
            field=models.ImageField(
                default="events/banners/event-banner-default.jpg",
                upload_to="events/banners/",
                verbose_name="Banner",
            ),
        ),
    ]
