# Generated by Django 5.1.3 on 2025-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0015_event_reviewed_at_event_reviewed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="reviewed_by",
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("closed", "Encerrado"),
                    ("canceled", "Cancelado"),
                    ("draft", "Rascunho"),
                    ("approved", "Aprovado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="",
            ),
        ),
    ]
