# Generated by Django 5.1.3 on 2025-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0016_remove_event_reviewed_at_remove_event_reviewed_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("closed", "Encerrado"),
                    ("canceled", "Cancelado"),
                    ("draft", "Não aprovado"),
                    ("approved", "Aprovado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="",
            ),
        ),
    ]
