# Generated by Django 5.1.3 on 2025-02-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0017_alter_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("closed", "Encerrado"),
                    ("canceled", "Cancelado"),
                    ("draft", "Não aprovado"),
                    ("approved", "Aprovado"),
                    ("recused", "Recusado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="",
            ),
        ),
    ]
