# Generated by Django 5.1.3 on 2025-02-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_certificate_image_alter_certificate_activity"),
        ("management", "0019_event_observation"),
    ]

    operations = []
