# Generated by Django 5.1.3 on 2025-02-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0020_merge_20250224_1320"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["init_date"], "verbose_name_plural": "Eventos"},
        ),
    ]
