# Generated by Django 5.1.3 on 2025-01-30 05:04
# pylint: disable=duplicate-code

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="eventos/",
                        verbose_name="Imagem do Evento",
                    ),
                ),
                ("inicio", models.DateField(verbose_name="Data de Início")),
                ("fim", models.DateField(verbose_name="Data de Fim")),
                ("horario_inicio", models.TimeField(verbose_name="Horário de Início")),
                (
                    "status_inicial",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=10,
                        verbose_name="Status Inicial",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tags"
                    ),
                ),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            (
                                "IFRN - campus pau dos ferros",
                                "IFRN - campus Pau dos Ferros",
                            )
                        ],
                        max_length=100,
                        verbose_name="Campus",
                    ),
                ),
                (
                    "organizadores",
                    models.EmailField(
                        max_length=254, verbose_name="Email do Organizador"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("inicio", models.DateField(verbose_name="Data de Início")),
                ("fim", models.DateField(verbose_name="Data de Fim")),
                ("horario_inicio", models.TimeField(verbose_name="Horário de Início")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("palestra", "Palestra"),
                            ("minicurso", "Minicurso"),
                            ("workshop", "Workshop"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Atividade",
                    ),
                ),
                (
                    "responsaveis",
                    models.CharField(max_length=255, verbose_name="Responsáveis"),
                ),
                (
                    "horas_previstas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Horas Previstas",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="management.evento",
                    ),
                ),
            ],
        ),
    ]
