# Generated by Django 5.1.3 on 2025-02-06 00:52
# pylint: disable=duplicate-code


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "migration_0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Atividade",
        ),
        migrations.DeleteModel(
            name="Evento",
        ),
    ]
