# Generated by Django 5.1.3 on 2025-02-06 00:57
# pylint: disable=duplicate-code


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "migration_0002_event_delete_atividade_delete_evento"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
