# Generated by Django 5.1.3 on 2025-02-19 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubscription",
            name="attendance_indentifier",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="eventsubscription",
            name="check_in_qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="checkin/qrcode/"),
        ),
        migrations.AddField(
            model_name="eventsubscription",
            name="is_checked_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsubscription",
            name="is_subcription_canceled",
            field=models.BooleanField(default=False),
        ),
    ]
