# Generated by Django 5.1.3 on 2025-02-19 09:52
import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("core", "EventSubscription")
    for row in MyModel.objects.all():
        row.attendance_indentifier = uuid.uuid4()
        row.save(update_fields=["attendance_indentifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_eventsubscription_attendance_indentifier_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
