# Generated by Django 5.1.3 on 2025-02-24 17:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_attendance_indentifier_uuid_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventsubscription",
            options={"verbose_name": "Inscrições em Evento"},
        ),
    ]
