# Generated by Django 5.1.3 on 2025-02-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(max_length=170, unique=True, verbose_name="email"),
        ),
    ]
