# Generated by Django 5.1.3 on 2025-02-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_participant_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="cpf",
            field=models.CharField(max_length=70, verbose_name="cpf"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="password",
            field=models.CharField(max_length=70, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone",
            field=models.CharField(max_length=70, verbose_name="phone"),
        ),
    ]
