# Generated by Django 5.1.3 on 2025-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_participant_cpf_alter_participant_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="cpf",
            field=models.CharField(max_length=11, verbose_name="cpf"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone",
            field=models.CharField(max_length=16, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="username",
            field=models.CharField(max_length=150, verbose_name="username"),
        ),
    ]
