# Generated by Django 5.1.3 on 2025-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_participant_cpf_alter_participant_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
