# Generated by Django 5.1.3 on 2025-02-12 18:42

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_participant_password"),
        (
            "management",
            "0005_alter_activity_options_alter_certificate_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicIntern",
            fields=[
                (
                    "participant_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suap_itern_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(verbose_name="registration_number"),
                ),
                ("association_type", models.CharField(verbose_name="association_type")),
            ],
            options={
                "verbose_name_plural": "Academicos Internos",
            },
            bases=("accounts.participant",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "participant_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "administrator_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Administradores",
            },
            bases=("accounts.participant",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={"verbose_name_plural": "Participantes"},
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "participant_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "events_managed",
                    models.ManyToManyField(
                        related_name="organizer",
                        to="management.event",
                        verbose_name="Eventos gerenciados",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Organizadores",
            },
            bases=("accounts.participant",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
