# Generated by Django 5.1.3 on 2025-02-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_academicintern_administrator_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academicintern",
            old_name="suap_itern_id",
            new_name="suap_intern_id",
        ),
    ]
